### PR TITLE
Add a client API

### PR DESCRIPTION
**Pull request by hannahhoward**
# Goals

Adds an API for interacting with singularity over HTTP or through code

# Implementation

- refactor errors so handlers no longer require HTTP codes, but are also identifiable by type
- move conversion of errors to response codes to the api handler
- clean up some of the error generation
- add a client interface (so far, just what Motion needs, but to be expanded upon)
- add a direct code implementation and a implementation based on the HTTP API

### CODE REVIEW

**Review by xinaxu — APPROVED** [review]
Thanks for all the effort spent to refactor the code

**Comment by masih** [comment]
Was there a specific reason for not auto generating the HTTP client library from swagger?

**Comment by hannahhoward** [comment]
I don't think it would be quite the same.

**Comment by hannahhoward** [comment]
also, I didn't know that was a thing :P

**Comment by hannahhoward** [comment]
The intent is for the local and HTTP clients to be identical in signature.

**Comment by masih** [comment]
> The intent is for the local and HTTP clients to be identical in signature

I am curious what is the reason for aiming to maintain the same signature between the two? The scope of HTTP APIs suggests that its implementation could require significant effort, and maintaining consistency might be quite a task as we move forward.

Could it be that we are not necessarily striving for a direct 1:1 HTTP client implementation here, despite the potential implications of the package name? It seems more likely that we're looking at a form of "Remote" client (please forgive the improvised term). Such a client might encapsulate multiple HTTP calls within a single API request, implementing specific logic that the HTTP API doesn't directly expose. If this is the case, it might be worth considering a package renaming to minimize any possible confusion regarding its API mirroring the HTTP API one-on-one.

**Pull request merged**
