### PR TITLE
Text corrections

### PR DESCRIPTION
**Pull request by criadoperez**
Replaces PR #359 
Text corrections on multiple files. 
`make generate` and `make lint` passed.

### CODE REVIEW

**Comment by xinaxu** [comment]
hmm. Not sure why the generated file is different for you.
If you checkout to main branch and run `make generate` will it show any modified files after the generation?

**Comment by xinaxu** [comment]
Try run this workflow in your forked repo.
https://github.com/data-preservation-programs/singularity/actions/workflows/auto-generate.yml

**Comment by criadoperez** [comment]
> hmm. Not sure why the generated file is different for you. If you checkout to main branch and run `make generate` will it show any modified files after the generation?

Running `make generate` on `main` produced change on 4 files. As `main` updated recently I also later synced my fork and run `make generate` again producing the same results. Modifying the same 4 files.

```
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   docs/en/SUMMARY.md
        modified:   docs/en/cli-reference/storage/create/README.md
        modified:   docs/en/cli-reference/storage/update/README.md
        modified:   handler/storage/types_gen.go

no changes added to commit (use "git add" and/or "git commit -a")

```

**Comment by xinaxu** [comment]
From the changed file, it seems like this may be able to fix the discrepancy here.
https://github.com/data-preservation-programs/singularity/pull/376

**Comment by criadoperez** [comment]
It seems that that made the trick. Finally all checks passed :-)

**Pull request merged**
