### PR TITLE
Analytics Collection

### PR DESCRIPTION
**Pull request by xinaxu**
Upon completion of packing job and successful deal proposal
* Events are collected and published to Singualrity Metrics API https://github.com/data-preservation-programs/singularity-metrics/blob/main/handler/v2/handler.go
* Those metrics are then aggregated and rendered on the dashboard https://singularity-metrics-dashboard.vercel.app/

Events are grouped and published once every hour, or upon termination of the process. It's only applicable to
* API - when `pack` or `send-manual` APIs are called
* dataset worker - when pack job completes
* deal pusher - when a deal proposal is accepted by an SP

Using `send-manual` CLI will not publish any event.

Metrics collection can be disabled by setting `SINGULARITY_METRICS` env to `0`

### CODE REVIEW

**Comment by masih** [comment]
Questions:
* Is there a particular reason for Singularity to roll out its own dashboard / metrics collection mechanism?
* Have you considered using Prometheus metrics integration?

**Comment by xinaxu** [comment]
@masih 
> Is there a particular reason for Singularity to roll out its own dashboard / metrics collection mechanism?
> Have you considered using Prometheus metrics integration?

They are for quite different purposes. The metrics here collected is to track and only track the usage, rather than health monitoring of the software. We want to collect all piece_cids for all users and then did some aggregation in our own database for further OKR tracking, business analysis, etc. Those metrics are not meant for individual users.

We could, in additional to usage tracking here, offer prometheus metrics integration to integrate with individual user's internal prometheus server. We know some V1 users have been using standard prometheus at the system level but there is no ask for a application specific metrics monitoring yet.

**Comment by masih** [comment]
> The metrics here collected is to track and only track the usage, rather than health monitoring of the software.

I see thank you. 

In that case may i suggest renaming this feature to "analytics" or something along those lines? 

This is to avoid confusion with ops/ system health metrics (that we will add eventually?) which will most likely exported to prometheus instances operated by whoever running singularity.

**Comment by xinaxu** [comment]
> In that case may i suggest renaming this feature to "analytics" or something along those lines?

Sounds good

> ops/ system health metrics (that we will add eventually?)

Not sure, I'm trying to avoid implementing something that nobody has asked for. But I'll start bringing this up with customers in upcoming events and see if people are interested in this.

**Comment by masih** [comment]
> nobody has asked for

Please feel free to deprioritise this. When the time comes to measure throughput etc. metric collection seems inevitable. But until then we can leave it in the backlog.

**Comment by xinaxu** [comment]
#299

**Pull request merged**
